name: "build clojure application"
on:
  push:
    branches:
      - gh-actions
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Compile clojure
      run: nix build
    - name: Compile website
      run: clj -m cljs.main -d "out" -c demo.static-website -r
    - name: Disable Jekyll rendering
      run: touch build/site/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
